---
- name: time and timezone config
  hosts: localhost
  connection: local
  gather_facts: no
  no_log: "{{ debugMode }}"
  vars:
    # Heat sends ntpSerers list as a unicode string.  Cant use that directly but we can
    # initialize a new variable which understands the source format
    ntp: "{{ ntpServers }}"
  tasks:
    - selinux:
        policy: targeted
        state: permissive
      become: yes
    - name: set the local timezone
      timezone:
        name: "{{ timezone }}"
      become: yes
    - selinux:
        policy: targeted
        state: enforcing
      become: yes
    - name: stop chronyd
      service:
        name: chronyd
        state: stopped
      become: yes
    - name: enable chronyd
      service:
        name: chronyd
        enabled: yes
      become: yes
    - name: clean stock server lines from chrony.conf
      lineinfile:
        path: /etc/chrony.conf
        regexp: '^server '
        state: absent
      become: yes
    - name: add example ntp servers
      lineinfile:
        path: /etc/chrony.conf
        line: "server {{ item }} iburst"
      with_items:
        - "{{ ntp }}"
      become: yes
    - name: pump the local clock
      shell:
        cmd: "/bin/env ntpdate {{ ntp[0] }}"
      become: yes
    - name: start chronyd
      service:
        name: chronyd
        state: restarted
      become: yes
    - name: clean stock server lines from ntp.conf
      lineinfile:
        path: /etc/ntp.conf
        regexp: '^server '
        state: absent
      become: yes
    - name: add example ntp servers for legacy ntp.conf
      lineinfile:
        path: /etc/ntp.conf
        line: "server {{ item }} iburst"
      with_items:
        - "{{ ntp }}"
      become: yes
