heat_template_version: 2013-05-23

parameters:
  volsize:
    type: number
    default: 128
    constraints:
      - range: { min: 1, max: 1024 }

  instance_id:
    type: string
  voltype:
    type: string
    
resources:

  volume:
    type: OS::Cinder::Volume
    properties:
      size:
        get_param: volsize
      description: "cfme data disk"
      volume_type:
        get_param: voltype

  attachment:
    type: OS::Cinder::VolumeAttachment
    properties:
      volume_id:
        get_resource: volume
      instance_uuid:
        get_param: instance_id
